import {
  Code2, Palette, Globe, ShoppingCart, Layout, Cpu, Bot,
  Database, BarChart3, Shield, Zap, Smartphone, LineChart,
  Building2, Stethoscope, UtensilsCrossed, Scale, Users, Factory,
} from 'lucide-react';

export const services = [
  {
    title: 'Landing Pages',
    description: 'Páginas de alta conversão para campanhas e produtos.',
    benefits: ['Design persuasivo', 'CTA estratégicos', 'Carregamento ultrarrápido', 'SEO otimizado'],
    timeframe: '5-7 dias',
    price: 'R$ 600 - R$ 1.500',
    icon: 'Layout',
    slug: 'landing-pages',
  },
  {
    title: 'Sites Institucionais',
    description: 'Presença digital profissional para sua empresa.',
    benefits: ['Design exclusivo', 'Blog integrado', 'Painel administrativo', 'Multipáginas'],
    timeframe: '7-15 dias',
    price: 'R$ 1.200 - R$ 3.000',
    icon: 'Globe',
    slug: 'sites-institucionais',
  },
  {
    title: 'Sites para Clínicas',
    description: 'Sites profissionais para consultórios e clínicas.',
    benefits: ['Agendamento online', 'Prontuário digital', 'Galeria de antes/depois', 'FAQ automático'],
    timeframe: '7-12 dias',
    price: 'R$ 1.500 - R$ 3.500',
    icon: 'Stethoscope',
    slug: 'sites-clinicas',
  },
  {
    title: 'Sites para Restaurantes',
    description: 'Cardápio digital e site completo para restaurantes.',
    benefits: ['Cardápio interativo', 'Pedidos online', 'Galeria de pratos', 'Reservas'],
    timeframe: '7-12 dias',
    price: 'R$ 1.200 - R$ 3.500',
    icon: 'UtensilsCrossed',
    slug: 'sites-restaurantes',
  },
  {
    title: 'Sites para Advogados',
    description: 'Sites profissionais para escritórios de advocacia.',
    benefits: ['Áreas de atuação', 'Artigos jurídicos', 'Agenda de consultas', 'Portfólio de casos'],
    timeframe: '7-10 dias',
    price: 'R$ 1.200 - R$ 3.500',
    icon: 'Scale',
    slug: 'sites-advogados',
  },
  {
    title: 'E-commerce',
    description: 'Lojas virtuais completas para vender online.',
    benefits: ['Catálogo de produtos', 'Carrinho inteligente', 'Pagamentos integrados', 'Gestão de pedidos'],
    timeframe: '15-30 dias',
    price: 'R$ 2.500 - R$ 8.000',
    icon: 'ShoppingCart',
    slug: 'ecommerce',
  },
  {
    title: 'Portais',
    description: 'Portais institucionais e plataformas de conteúdo.',
    benefits: ['Multi-usuário', 'Gestão de conteúdo', 'Área restrita', 'Notificações'],
    timeframe: '20-40 dias',
    price: 'R$ 3.000 - R$ 10.000',
    icon: 'Building2',
    slug: 'portais',
  },
  {
    title: 'Sistemas Web',
    description: 'Sistemas personalizados para automatizar processos.',
    benefits: ['Automação de processos', 'Relatórios', 'Gestão de dados', 'Integrações'],
    timeframe: '15-40 dias',
    price: 'R$ 4.000 - R$ 15.000',
    icon: 'Code2',
    slug: 'sistemas-web',
  },
  {
    title: 'Micro SaaS',
    description: 'Produtos SaaS prontos para escalar.',
    benefits: ['Multi-inquilino', 'Planos de assinatura', 'Dashboard analítico', 'API pública'],
    timeframe: '30-60 dias',
    price: 'A partir de R$ 5.000',
    icon: 'Cpu',
    slug: 'micro-saas',
  },
  {
    title: 'Automações',
    description: 'Automações inteligentes para eliminar tarefas repetitivas.',
    benefits: ['Economia de horas', 'Zero erro humano', 'Relatórios automáticos', 'Integração WhatsApp/Email'],
    timeframe: '5-15 dias',
    price: 'R$ 800 - R$ 3.000',
    icon: 'Zap',
    slug: 'automacoes',
  },
  {
    title: 'Inteligência Artificial',
    description: 'Soluções com IA para transformar seu negócio.',
    benefits: ['Chatbots inteligentes', 'Análise preditiva', 'Processamento de dados', 'Visão computacional'],
    timeframe: '15-45 dias',
    price: 'A partir de R$ 3.000',
    icon: 'Bot',
    slug: 'inteligencia-artificial',
  },
  {
    title: 'Dashboards',
    description: 'Painéis interativos com dados em tempo real.',
    benefits: ['Visualização dinâmica', 'Exportação de dados', 'Filtros avançados', 'Alertas inteligentes'],
    timeframe: '10-25 dias',
    price: 'R$ 2.000 - R$ 6.000',
    icon: 'BarChart3',
    slug: 'dashboards',
  },
  {
    title: 'APIs & Integrações',
    description: 'APIs robustas para conectar seus sistemas.',
    benefits: ['Documentação automática', 'Versionamento', 'Escalabilidade', 'Segurança'],
    timeframe: '10-25 dias',
    price: 'R$ 2.000 - R$ 8.000',
    icon: 'Database',
    slug: 'apis-integracoes',
  },
  {
    title: 'CRM',
    description: 'Sistemas de gestão de relacionamento com clientes.',
    benefits: ['Pipeline de vendas', 'Histórico completo', 'Automação de marketing', 'Relatórios'],
    timeframe: '20-45 dias',
    price: 'R$ 5.000 - R$ 15.000',
    icon: 'Users',
    slug: 'crm',
  },
  {
    title: 'ERP',
    description: 'Sistemas de gestão empresarial completos.',
    benefits: ['Gestão financeira', 'Controle de estoque', 'RH integrado', 'Nota fiscal'],
    timeframe: '30-90 dias',
    price: 'Sob consulta',
    icon: 'Factory',
    slug: 'erp',
  },
];

export const portfolioItems = [
  {
    title: 'Ilíria Psicologia',
    category: 'Clínicas',
    image: '/portfolio/clinica.jpg',
    description: 'Site profissional para clínica de psicologia, focado em conversão e agendamento de consultas.',
    objective: 'Aumentar a captação de pacientes e profissionalizar a presença digital.',
    problem: 'Necessidade de um canal oficial para transmitir confiança aos pacientes.',
    solution: 'Landing page otimizada com design acolhedor e botões de ação diretos para agendamento.',
    technologies: ['React', 'Next.js', 'Tailwind CSS'],
    result: 'Aumento significativo na taxa de conversão de visitantes para pacientes.',
    link: 'https://iliria-psicologia.vercel.app/',
    github: '#',
  },
  {
    title: 'Mantovisk',
    category: 'Institucional',
    image: '/portfolio/advocacia.jpg',
    description: 'Site institucional moderno e de alta performance.',
    objective: 'Criar uma presença online forte e memorável.',
    problem: 'Falta de posicionamento digital adequado para o nível da marca.',
    solution: 'Design exclusivo com animações fluidas e navegação intuitiva.',
    technologies: ['Next.js', 'Framer Motion', 'Tailwind CSS'],
    result: 'Maior engajamento dos usuários e percepção de valor da marca.',
    link: 'https://mantovisk.vercel.app/',
    github: '#',
  },
  {
    title: 'Miracle House Architecture',
    category: 'Institucional',
    image: '/portfolio/dashboard.jpg',
    description: 'Portfólio digital para escritório de arquitetura.',
    objective: 'Exibir projetos de arquitetura de forma elegante e imersiva.',
    problem: 'Dificuldade em apresentar a qualidade visual dos projetos em plataformas comuns.',
    solution: 'Site focado em imagens de alta resolução com layout minimalista.',
    technologies: ['React', 'Next.js', 'Tailwind CSS'],
    result: 'Aumento no número de contatos para orçamentos de projetos premium.',
    link: 'https://miracle-house-architect-studio.vercel.app/',
    github: '#',
  },
  {
    title: 'Saitama Sushi',
    category: 'Restaurantes',
    image: '/portfolio/restaurante.jpg',
    description: 'Site atraente para restaurante japonês com cardápio digital.',
    objective: 'Atrair mais clientes para o restaurante e facilitar o acesso ao cardápio.',
    problem: 'Dependência exclusiva de apps de delivery e redes sociais.',
    solution: 'Site próprio com fotos apetitosas, cardápio online e informações de contato.',
    technologies: ['Next.js', 'Tailwind CSS'],
    result: 'Fortalecimento da marca e aumento de reservas/pedidos diretos.',
    link: 'https://saitama-sushi.vercel.app/',
    github: '#',
  },
  {
    title: 'Valhallas Motors',
    category: 'Ecommerce',
    image: '/portfolio/ecommerce.jpg',
    description: 'Plataforma digital para concessionária de veículos de luxo.',
    objective: 'Exibir o estoque de veículos com detalhes técnicos e fotos de alta qualidade.',
    problem: 'Processo de venda complexo sem uma vitrine digital adequada.',
    solution: 'Catálogo online de veículos com filtros avançados e formulário de interesse.',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    result: 'Geração de leads qualificados para a equipe de vendas.',
    link: 'https://valhallas-motors.vercel.app/',
    github: '#',
  },
  {
    title: 'VitrineLux Carros',
    category: 'Ecommerce',
    image: '/portfolio/ecommerce.jpg',
    description: 'Sistema de vitrine de estoque para loja de carros.',
    objective: 'Gerenciar e expor o estoque de veículos de forma eficiente.',
    problem: 'Dificuldade em manter o estoque atualizado e visível para os clientes.',
    solution: 'Plataforma rápida com listagem de veículos e fácil navegação.',
    technologies: ['React', 'Next.js', 'Tailwind CSS'],
    result: 'Maior agilidade na atualização do estoque e consultas de clientes.',
    link: 'https://vitrinelux-carros-54u4.vercel.app/estoque',
    github: '#',
  },
  {
    title: 'Porsche Experience (Artconcept)',
    category: 'Institucional',
    image: '/portfolio/ecommerce.jpg',
    description: 'Conceito visual imersivo para marca automotiva de alto padrão.',
    objective: 'Demonstrar habilidades de design avançado e criação de experiências.',
    problem: 'Mostrar capacidade de criar interfaces premium e interativas.',
    solution: 'Design arrojado, uso intenso de animações 3D/paralaxe e estética sofisticada.',
    technologies: ['Next.js', 'Three.js', 'Tailwind CSS', 'Framer Motion'],
    result: 'Portfólio enriquecido com um projeto de altíssimo impacto visual.',
    link: 'https://posrche-site-exp.vercel.app/',
    github: '#',
  },
  {
    title: 'Aston Martin (Artconcept)',
    category: 'Institucional',
    image: '/portfolio/ecommerce.jpg',
    description: 'Projeto conceito explorando a elegância e performance da Aston Martin.',
    objective: 'Criar uma landing page conceitual focada em design e interatividade.',
    problem: 'Diferenciar o portfólio com projetos de padrão internacional.',
    solution: 'Interface limpa, tipografia elegante e transições suaves.',
    technologies: ['React', 'Next.js', 'Tailwind CSS'],
    result: 'Excelente peça de demonstração para clientes que buscam alto padrão.',
    link: 'https://aston-martin-psi.vercel.app/',
    github: '#',
  }
];
export const processSteps = [
  { step: '01', title: 'Briefing Estratégico', desc: 'Realizamos uma reunião detalhada para entender profundamente seu negócio, objetivos, público-alvo e desafios específicos. Nesta etapa, coletamos todas as informações necessárias para alinhar expectativas e definir o escopo do projeto.' },
  { step: '02', title: 'Pesquisa & Análise', desc: 'Estudamos o mercado, concorrência, tendências e comportamento do seu público. Analisamos dados para criar uma estratégia personalizada que maximize os resultados do seu projeto digital.' },
  { step: '03', title: 'Design & Prototipagem', desc: 'Criamos o design visual do seu site/sistema com foco em UX/UI moderna e conversão. Você aprova o design antes de começarmos o desenvolvimento, garantindo que tudo esteja conforme sua visão.' },
  { step: '04', title: 'Desenvolvimento', desc: 'Codificamos seu projeto com tecnologias modernas (Next.js, React, Tailwind), seguindo as melhores práticas de performance, segurança e SEO. Mantemos você atualizado durante todo o processo.' },
  { step: '05', title: 'Testes & Ajustes', desc: 'Realizamos testes rigorosos em todos os dispositivos e navegadores. Verificamos performance, responsividade, segurança e funcionalidades. Ajustamos até que tudo esteja perfeito.' },
  { step: '06', title: 'Lançamento & Entrega', desc: 'Publicamos seu projeto na hospedagem, configuramos domínio e SSL. Fazemos o treinamento para que você saiba usar tudo. Entregamos um projeto 100% funcional e pronto para usar!' },
  { step: '07', title: 'Suporte & Otimização', desc: 'Oferecemos suporte contínuo após o lançamento. Monitoramos o desempenho, aplicamos atualizações e otimizações para garantir que seu projeto continue evoluindo e gerando resultados.' },
];


export const differentiators = [
  { title: "Código Limpo", desc: "Código organizado, documentado e seguindo as melhores práticas.", icon: "Code2" },
  { title: "Alta Performance", desc: "Sites com carregamento instantâneo e pontuação 95+ no Lighthouse.", icon: "Zap" },
  { title: "SEO Premium", desc: "Otimização completa para Google com Schema.org e meta tags.", icon: "Globe" },
  { title: "Responsividade", desc: "Experiência perfeita em qualquer dispositivo.", icon: "Smartphone" },
  { title: "Segurança", desc: "Proteção contra vulnerabilidades, SSL e HTTPS.", icon: "Shield" },
  { title: "Escalabilidade", desc: "Arquitetura preparada para crescer sem perder performance.", icon: "LineChart" },
  { title: "Integrações", desc: "Conectamos com APIs e ferramentas que você já usa.", icon: "Database" },
  { title: "Suporte Premium", desc: "Suporte dedicado com tempo de resposta rápido.", icon: "Users" },
  { title: "Inteligência Artificial", desc: "Soluções com IA para automatizar seu negócio.", icon: "Bot" },
];

export const testimonials = [
  {
    quote: 'O site ficou muito acima do que a gente esperava. Os agendamentos pelo site aumentaram e os pacientes elogiam o visual todo santo dia.',
    author: 'Equipe Ilíria Psicologia',
    role: 'Clínica de Psicologia',
    project: 'Ilíria Psicologia',
  },
  {
    quote: 'Processo transparente do início ao fim. Cada etapa foi validada com a gente antes de seguir, sem surpresa no final.',
    author: 'Direção Mantovisk',
    role: 'Institucional',
    project: 'Mantovisk',
  },
  {
    quote: 'Precisávamos de um portfólio que realmente mostrasse a qualidade dos projetos de arquitetura. Entregaram exatamente isso.',
    author: 'Miracle House Architecture',
    role: 'Escritório de Arquitetura',
    project: 'Miracle House Architecture',
  },
  {
    quote: 'O cardápio digital facilitou demais o dia a dia do restaurante e os clientes adoram poder ver os pratos antes de pedir.',
    author: 'Equipe Saitama Sushi',
    role: 'Restaurante',
    project: 'Saitama Sushi',
  },
  {
    quote: 'A vitrine online organizou nosso estoque e gerou contatos qualificados desde a primeira semana no ar.',
    author: 'Valhallas Motors',
    role: 'Concessionária de Veículos',
    project: 'Valhallas Motors',
  },
];

export const plans = [
  { name: "Landing Page", description: "Perfeito para campanhas", price: "R$ 797", originalPrice: "R$ 1.500", features: ["1 página", "SEO básico", "Formulário"], timeframe: "5-7 dias", popular: false },
  { name: "Site Institucional", description: "Presença digital", price: "R$ 1.497", originalPrice: "R$ 2.500", features: ["Até 5 páginas", "Blog", "SEO completo", "Responsivo"], timeframe: "7-15 dias", popular: true },
  { name: "Site Premium", description: "Solução completa", price: "R$ 2.997", originalPrice: "R$ 5.000", features: ["Páginas ilimitadas", "Design Exclusivo", "Integrações"], timeframe: "20-40 dias", popular: false },
  { name: "Loja Virtual", description: "E-commerce", price: "R$ 3.997", originalPrice: "R$ 8.000", features: ["Catálogo", "Carrinho", "Pagamentos", "Painel Gestão"], timeframe: "20-35 dias", popular: false },
  { name: "Sistema Web", description: "Sistema personalizado", price: "Sob consulta", originalPrice: "", features: ["Funcionalidades sob medida", "Banco de dados"], timeframe: "15-60 dias", popular: false },
  { name: "Projeto Personalizado", description: "Solução sob medida", price: "Sob consulta", originalPrice: "", features: ["Consultoria", "Projeto exclusivo", "Suporte"], timeframe: "30-90 dias", popular: false },
];

export const faqItems = [
  { q: "Quanto tempo leva?", a: "Landing pages em 5-7 dias, sites em 10-15 dias." },
  { q: "Preciso ter conhecimento técnico?", a: "Não! Cuidamos de tudo." },
  { q: "Oferecem suporte?", a: "Sim! Todos os projetos incluem suporte." },
  { q: "O site será responsivo?", a: "Sim! 100% responsivo." },
  { q: "Vem com SEO?", a: "Sim! SEO técnico completo." },
  { q: "Posso atualizar depois?", a: "Sim! Com painel administrativo." },
  { q: "Integram com WhatsApp?", a: "Sim! Integração inclusa." },
];

export const blogPosts = [
  {
    title: "Por que seu negócio precisa de um site profissional?",
    excerpt: "Descubra como um site profissional pode transformar seus resultados.",
    category: "Marketing Digital",
    date: "12 Jun 2026",
    author: "Valhallas TechForge",
    slug: "por-que-site-profissional",
    tags: ["Marketing", "Presença Digital"],
    content: [
      "Hoje em dia, o site da sua empresa costuma ser o primeiro contato que um cliente em potencial tem com o seu negócio — antes mesmo de uma ligação ou de uma visita. Se essa primeira impressão for de um site lento, desatualizado ou que não funciona bem no celular, é bem provável que esse cliente feche a aba e procure a concorrência.",
      "Um site profissional não é apenas uma vitrine bonita. Ele organiza a forma como você apresenta seus serviços, facilita o contato (formulário, WhatsApp, e-mail), melhora seu posicionamento no Google e passa credibilidade imediata — algo que redes sociais sozinhas não conseguem entregar da mesma forma.",
      "Empresas que investem em um site bem estruturado costumam notar três efeitos práticos: mais pedidos de orçamento, menos perguntas repetidas (porque a informação já está no site) e uma percepção de valor mais alta por parte do cliente, o que ajuda inclusive a justificar preços mais altos pelos seus produtos ou serviços.",
      "Se o seu negócio ainda não tem um site, ou tem um site antigo que não representa mais o nível do seu trabalho, esse é geralmente um dos investimentos com retorno mais rápido e mensurável que você pode fazer este ano.",
    ],
  },
  {
    title: "IA nos Negócios: Guia Completo",
    excerpt: "Como a IA pode automatizar processos e economizar horas do seu time.",
    category: "Tecnologia",
    date: "28 Mai 2026",
    author: "Valhallas TechForge",
    slug: "ia-nos-negocios",
    tags: ["IA", "Automação"],
    content: [
      "Inteligência artificial deixou de ser um assunto só de grandes empresas de tecnologia. Hoje, negócios de todos os tamanhos conseguem usar IA para automatizar tarefas repetitivas, responder clientes mais rápido e tomar decisões com base em dados reais.",
      "Os casos de uso mais comuns que vemos em projetos reais incluem: chatbots que qualificam leads antes de chegar para um vendedor humano, automações que organizam pedidos e agendamentos sem intervenção manual, e análises preditivas que ajudam a antecipar demanda ou identificar clientes com risco de cancelamento.",
      "O erro mais frequente é tentar automatizar tudo de uma vez. O caminho que funciona na prática é mapear os dois ou três processos que mais consomem tempo da equipe hoje, e resolver esses primeiro — o retorno costuma aparecer em semanas, não em meses.",
      "Se o seu negócio depende de atendimento repetitivo, planilhas manuais ou processos que várias pessoas fazem 'do jeito que sempre fizeram', existe uma boa chance de que uma automação simples já resolva boa parte da dor.",
    ],
  },
  {
    title: "SEO em 2026: o que realmente funciona",
    excerpt: "As estratégias de SEO que continuam trazendo resultado este ano.",
    category: "SEO",
    date: "14 Mai 2026",
    author: "Valhallas TechForge",
    slug: "seo-2024",
    tags: ["SEO", "Google"],
    content: [
      "SEO continua sendo uma das formas mais baratas de atrair clientes a longo prazo, mas a forma de fazer certo mudou bastante nos últimos anos. Não basta mais 'colocar palavras-chave' no texto — o Google avalia performance técnica, experiência do usuário e relevância real do conteúdo.",
      "Os pontos que mais impactam o ranqueamento atualmente são: velocidade de carregamento (principalmente no celular), estrutura técnica correta (títulos, meta descrições, dados estruturados), conteúdo que responde de fato à dúvida da pessoa que pesquisou, e sinais de confiança como avaliações e presença consistente em diferentes canais.",
      "Outro ponto que muita empresa ignora é o SEO local: para negócios que atendem uma região específica (clínicas, restaurantes, escritórios), aparecer bem no Google Maps e nas buscas locais costuma trazer resultado mais rápido do que competir por termos genéricos e concorridos.",
      "SEO não é mágica nem instantâneo, mas é construído — quanto antes seu site tiver a base técnica correta, mais rápido os resultados começam a aparecer.",
    ],
  },
  {
    title: "Como Escolher a Tecnologia Ideal para o Seu Projeto",
    excerpt: "Next.js, React, Node.js: qual faz sentido para cada tipo de projeto.",
    category: "Desenvolvimento",
    date: "30 Abr 2026",
    author: "Valhallas TechForge",
    slug: "escolher-tecnologia",
    tags: ["Desenvolvimento", "Tecnologia"],
    content: [
      "Uma dúvida comum de quem está contratando um site ou sistema é: 'qual tecnologia vocês usam, e por quê?'. A resposta certa depende do objetivo do projeto, não de qual tecnologia está mais na moda.",
      "Para sites institucionais e landing pages, o Next.js (com React) é geralmente a escolha certa: carregamento rápido, bom para SEO e fácil de manter no longo prazo. Para sistemas mais complexos, com login, banco de dados e regras de negócio específicas, entra também um backend robusto como Node.js, com banco de dados adequado ao volume de dados esperado.",
      "O erro mais comum que vemos em projetos que já vieram de outras empresas é o uso de tecnologias genéricas demais para o que o negócio precisa — o que gera lentidão, dificuldade de manutenção e custo mais alto lá na frente para qualquer alteração.",
      "Na prática, o mais importante não é o nome da tecnologia, e sim se a arquitetura escolhida aguenta o crescimento do seu negócio nos próximos anos sem precisar ser refeita do zero.",
    ],
  },
  {
    title: "UI/UX Design: o diferencial entre sites comuns e premium",
    excerpt: "Por que o design certo converte mais visitantes em clientes.",
    category: "Design",
    date: "18 Abr 2026",
    author: "Valhallas TechForge",
    slug: "ui-ux-design",
    tags: ["Design", "UX"],
    content: [
      "Existe uma diferença clara entre um site que 'parece bonito' e um site que foi desenhado para converter. A primeira é uma questão estética; a segunda envolve entender como a pessoa que visita seu site pensa, decide e age.",
      "Um bom design de UX organiza a informação na ordem que o visitante precisa dela: o que você faz, para quem, por que confiar em você, e como agir (comprar, agendar, pedir orçamento). Um bom design de UI cuida da parte visual — tipografia legível, cores consistentes, espaçamento e hierarquia — para que essa jornada seja fácil e agradável.",
      "Pequenos detalhes fazem diferença real na conversão: um botão de ação visível sem precisar rolar a página, um formulário curto demais para desanimar preenchimento, ou uma velocidade de carregamento que não frustra o visitante nos primeiros segundos.",
      "Sites 'premium' não são só mais bonitos — eles são pensados estrategicamente para reduzir o atrito entre a curiosidade do visitante e a ação que você quer que ele tome.",
    ],
  },
];